# Generated by Django 5.0.6 on 2024-09-07 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='baths',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='beds',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='room',
            name='max_adults',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='room',
            name='max_children',
            field=models.IntegerField(default=1),
        ),
    ]
