# Generated by Django 4.2.15 on 2024-10-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_adults_booking_check_in_booking_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_con',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
